from pysb import *
Model()
Parameter('kp1', 1)
Parameter('km1', 1)
Parameter('kp2', 1)
Parameter('km2', 1)
Parameter('kp3', 1)
Parameter('km3', 1)
Parameter('R0', 3e5)
Parameter('L0', 3e5)
Initial(R(r,r), Parameter("R(r,r_0",R0))
Initial(L(l,l), Parameter("L(l,l_0",L0))
Rule("rule_0", R(r) + L(l,l)  >>  R(r=1)%L(l=1,l) , kp1,km1)
Rule("rule_1", R(r) + L(l,l=+)  >>  R(r=1)%L(l=1,l=+) , kp2,km2)
Rule("rule_2", R(r)%L(l)  >>  R(r=1)%L(l=1) , kp3,km3)
